# Site settings
title: DesignFrags
email: adityadineshsaxena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! I'm a Frontend guy, and this is my Blog-O-Sphere ;-). Wonder if that's old.
  I work with McKinsey Digital Labs. If you wanna say 'Hi', you'll find me on Twitter.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.designfrags.com" # the base hostname & protocol for your site
twitter_username: adityasaxena
github_username:  adityadineshsaxena

# Build settings
markdown: kramdown
